spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  application:
    name: pedidos-ms
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka